exports.elementListMock = [
  {
    name: "Francium",
    symbol: "Fr",
    propertyId: { yearDiscovered: 1939 },
  },
  {
    name: "Protactinium",
    symbol: "Pa",
    propertyId: { yearDiscovered: 1913 },
  },
  {
    name: "Uranium",
    symbol: "U",
    propertyId: { yearDiscovered: 1789 },
  },
  {
    name: "Americium",
    symbol: "Am",
    propertyId: { yearDiscovered: 1944 },
  },
  {
    name: "Curium",
    symbol: "Cm",
    propertyId: { yearDiscovered: 1944 },
  },
  {
    name: "Berkelium",
    symbol: "Bk",
    propertyId: { yearDiscovered: 1949 },
  },
  {
    name: "Fermium",
    symbol: "Fm",
    propertyId: { yearDiscovered: 1952 },
  },
];

exports.elementNestedObjectList = [
  { name: "Magnesium", symbol: "Mg", propertyId: null },
  {
    name: "Aluminum",
    symbol: "Al",
    propertyId: {
      atomicNumber: 13,
      atomicMass: 26.981538,
      standardState: "Solid",
      oxidationStates: "+3",
      electronegativity: 1.61,
      atomicRadius: 184,
      ionizationEnergy: 5.986,
      electronAffinity: 0.441,
      electronConfiguration: "[Ne]3s2 3p1",
      meltingPoint: 933.437,
      boilingPoint: 2792,
      density: 2.7,
      groupBlock: "Post-transition metal",
      elementId: 13,
    },
  },
  { name: "Silicon", symbol: "Si", propertyId: null },
  { name: "Phosphorus", symbol: "P", propertyId: null },
  {
    name: "Sulfur",
    symbol: "S",
    propertyId: {
      atomicNumber: 16,
      atomicMass: 32.07,
      standardState: "Solid",
      oxidationStates: "+6, +4, -2",
      electronegativity: 2.58,
      atomicRadius: 180,
      ionizationEnergy: 10.36,
      electronAffinity: 2.077,
      electronConfiguration: "[Ne]3s2 3p4",
      meltingPoint: 388.36,
      boilingPoint: 717.75,
      density: 2.067,
      groupBlock: "Nonmetal",
      elementId: 16,
    },
  },
  { name: "Chlorine", symbol: "Cl", propertyId: null },
  { name: "Argon", symbol: "Ar", propertyId: null },
  { name: "Potassium", symbol: "K", propertyId: null },
  {
    name: "Calcium",
    symbol: "Ca",
    propertyId: {
      atomicNumber: 20,
      atomicMass: 40.08,
      standardState: "Solid",
      oxidationStates: "+2",
      electronegativity: 1,
      atomicRadius: 231,
      ionizationEnergy: 6.113,
      electronAffinity: "N/A",
      electronConfiguration: "[Ar]4s2",
      meltingPoint: 1115,
      boilingPoint: 1757,
      density: 1.54,
      groupBlock: "Alkaline earth metal",
      elementId: 20,
    },
  },
  { name: "Scandium", symbol: "Sc", propertyId: null },
  { name: "Titanium", symbol: "Ti", propertyId: null },
  { name: "Vanadium", symbol: "V", propertyId: null },
  { name: "Chromium", symbol: "Cr", propertyId: null },
  { name: "Manganese", symbol: "Mn", propertyId: null },
  {
    name: "Iron",
    symbol: "Fe",
    propertyId: {
      atomicNumber: 26,
      atomicMass: 55.84,
      standardState: "Solid",
      oxidationStates: "+3, +2",
      electronegativity: 1.83,
      atomicRadius: 194,
      ionizationEnergy: 7.902,
      electronAffinity: 0.163,
      electronConfiguration: "[Ar]4s2 3d6",
      meltingPoint: 1811,
      boilingPoint: 3134,
      density: 7.874,
      groupBlock: "Transition metal",
      elementId: 26,
    },
  },
];
