exports.propertyList = [
  {
    atomicNumber: 2,
    atomicMass: 4.0026,
    standardState: "Gas",
    oxidationStates: "0",
    electronegativity: "N/A",
    atomicRadius: 140,
    ionizationEnergy: 24.587,
    electronAffinity: "N/A",
    electronConfiguration: "1s2",
    meltingPoint: 0.95,
    boilingPoint: 4.22,
    density: 0.0001785,
    groupBlock: "Noble gas",
    yearDiscovered: 1868,
    elementId: { name: "Helium", symbol: "He" },
  },
  {
    atomicNumber: 75,
    atomicMass: 186.207,
    standardState: "Solid",
    oxidationStates: "+7, +6, +4",
    electronegativity: 1.9,
    atomicRadius: 217,
    ionizationEnergy: 7.88,
    electronAffinity: 0.15,
    electronConfiguration: "[Xe]6s2 4f14 5d5",
    meltingPoint: 3459,
    boilingPoint: 5869,
    density: 20.8,
    groupBlock: "Transition metal",
    yearDiscovered: 1925,
    elementId: { name: "Rhenium", symbol: "Re" },
  },
];
